#install common packages

- name: update apt cache
  action: apt update_cache=yes cache_valid_time=3600
  tags:
    - common
    - update

- name: install editor
  apt:
    pkg: ["vim"]
    state: present
  tags:
    - common
    - editor

- name: install version control tools
  apt:
    pkg: ["git"]
    state: present
  tags:
    - common
    - vcs

- name: install common python packages
  apt:
    pkg: ["python-setuptools", "python-pip", "python-dev", "python-pycurl"]
    state: present
  tags:
    - common
    - python

- name: install supervisor
  action: apt pkg={{ item }} state=installed
  with_items:
    - supervisor
  tags:
    - common
    - python
    - supervisor

- name: install virtualenv
  action: pip name={{ item }} state=present
  with_items:
    - virtualenv
  tags:
    - common
    - python
